// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOgwhOCk3Gkf0_wNyHi3JUnm62MorDUTw',
    appId: '1:943961182072:web:b03ae41255fa95ae11c28d',
    messagingSenderId: '943961182072',
    projectId: 'mynotes-flutter-bas',
    authDomain: 'mynotes-flutter-bas.firebaseapp.com',
    storageBucket: 'mynotes-flutter-bas.appspot.com',
    measurementId: 'G-442FLX0FCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAARbex1Ie7D3zIVymn_3l7yHDmCStd76o',
    appId: '1:943961182072:android:c66c13cabb54594e11c28d',
    messagingSenderId: '943961182072',
    projectId: 'mynotes-flutter-bas',
    storageBucket: 'mynotes-flutter-bas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPx0nbdYWrajGoOIJWAGW58RvIkCDt7ms',
    appId: '1:943961182072:ios:73d66daebe5e784511c28d',
    messagingSenderId: '943961182072',
    projectId: 'mynotes-flutter-bas',
    storageBucket: 'mynotes-flutter-bas.appspot.com',
    iosClientId: '943961182072-ekk929orim5lrvg23cdt9mnpd6c28i6e.apps.googleusercontent.com',
    iosBundleId: 'com.domain.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPx0nbdYWrajGoOIJWAGW58RvIkCDt7ms',
    appId: '1:943961182072:ios:73d66daebe5e784511c28d',
    messagingSenderId: '943961182072',
    projectId: 'mynotes-flutter-bas',
    storageBucket: 'mynotes-flutter-bas.appspot.com',
    iosClientId: '943961182072-ekk929orim5lrvg23cdt9mnpd6c28i6e.apps.googleusercontent.com',
    iosBundleId: 'com.domain.mynotes',
  );
}
